# Problem description

This notebook illustrates the use of the pyerfa library, which is based on the SOFA astronomy library in C, to transform coordinates from the a Terrestrial reference system to the Celestial reference system. 

Perform the coordinate transformation from Terrestrial to Celestial. The Celestial coordinates bellow are the desired answer.

COORDINATES | X (Km) |Y (Km) | Z (Km) | length (Km)
-|-|-|-|-
 TERRESTRIAL | -8187.60022| -14130.95891| 21138.03020| 26712.11557
 CELESTIAL | -2768.51569|  16094.22352| 21138.78919| 26712.11557

Use the following values from IERS bulletin B for day 122 of 2005:

XP (“) | Xerror (“) | YP (“) | Y error (“) |  UT1-UTC (DUT1) (“) | UT1-UTC (error) (“) 
-|-|-|-|-|-
-0,05723 | -0,00002 | 0,29734 | -0,00038 | -0,59713 | 0,94200



# Importing libraries



In [ ]:
!pip install pyerfa

In [ ]:
import erfa
import numpy as np

# Input data

In [ ]:
#HOR,MINU,SEGUNDO, ANO,MES,DIA,YEAR,MONTH;

Xp=-0.05723
Yp=0.29734
DUT1=-0.59713

ANO = 2005
MES = 5
DIA = 2
HOR = 0.0
MINU =0
SEGUNDO = 0.0

x=-8187.60022
y=-14130.95891
z=21138.03020

print("Terrestres:",x,y,z)
#print("Celestes:   ",Xc,Yc,Zc)

Terrestres: -8187.60022 -14130.95891 21138.0302


# Date time converstion from UTC to TT

In [ ]:
#DIA E HORA GPS PARA O SATÉLITE PRN 01

#Boletin do IERS - posicao do polo
XP = Xp*np.pi/648000.0;#em radianos
YP = Yp*np.pi/648000.0;
DUT1 = DUT1*np.pi/648000.0;
tempo = HOR*3600.0+MINU*60.0+SEGUNDO; # corresponde a 0h 0min 0seg
#Calendario Gregoriano para Data Juliana
aux=erfa.cal2jd(ANO, MES, DIA)
djm0,djm=aux
print("Dias julianos:",aux)
print("Dias julianos:",djm0+djm)
 #&djm0, &djm
RR=np.array([0,0,0])
RT=np.array([x,y,z])

#HORA UTC (DIFERE DA HORA GPS POR 13 SEGUNDOS)
UTC = tempo-13.0;
UT1 = UTC + DUT1;
TAI = UTC + 32.0; #!TEMPO ATOMICO INTERNACIONAL
TT = TAI + 32.184; #!TEMPO TERRESTRE

DATA1 = djm0;
DATA2 = djm + TT/(86400.0);

DATE2UT1 = djm + UT1/(86400.0);

Dias julianos: (2400000.5, 53492.0)
Dias julianos: 2453492.5


# Celestial to terrestrial rotation matrix with IAU 2000a method


In [ ]:
rc2t=erfa.c2t00a(DATA1, DATA2, DATA1, DATE2UT1, XP, YP)
print("Rotation Matrix c->t:")
print(rc2t)


Rotation Matrix c->t:
[[-7.67319128e-01 -6.41265301e-01  4.13070940e-04]
 [ 6.41265235e-01 -7.67319238e-01 -2.93239441e-04]
 [ 5.05001557e-04  3.98798009e-05  9.99999872e-01]]


# Using erfa's function to rotate the coordinates

In [ ]:
#multiplying the terrestrial coordinates RT with the transpose of the rotation matrix. Inverse transformation.
R_celestial=erfa.trxp(rc2t, RT) 
print("Celestial coordinates (km):         ",R_celestial)
print("Expected celestial coordinates: (km)",[-2768.51569,	16094.22352,	21138.78919])
#this would be used to perform the forward transformation.
#erfa.rxp(rc2t, RT) 

Celestial coordinates (km):          [-2768.51568811 16094.22351633 21138.78918259]
Expected celestial coordinates: (km) [-2768.51569, 16094.22352, 21138.78919]
